apiVersion: v1
kind: ConfigMap
metadata:
  name: cexvscex-config
  namespace: cexvscex
data:
  APP_ENV: "production"
  TRADING_SYMBOLS: "BTCUSDT,ETHUSDT"
  WS_PORT: "8080"
  INITIAL_EQUITY: "100000"
  APP_LOGGING__LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cexvscex
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "cexvscex-backend"
        static_configs:
          - targets: ["backend-svc:9090"]
